# Generated by Django 2.2.6 on 2019-10-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('line_number', models.IntegerField()),
                ('night_route', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=10)),
                ('station_name', models.CharField(max_length=30)),
                ('line', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='line.Line')),
            ],
        ),
    ]
