# Generated by Django 2.2.6 on 2019-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
