# Generated by Django 2.2.6 on 2019-10-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='night_route',
            field=models.BooleanField(default=False),
        ),
    ]
