# Generated by Django 2.2.6 on 2019-10-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_auto_20191023_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lng', models.DecimalField(decimal_places=3, max_digits=5)),
                ('station_name', models.CharField(max_length=30)),
            ],
        ),
    ]
